version: '3.8'

services:
  vivi-app:
    container_name: vivi_assistant
    build: .
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      # Nếu bạn muốn gán cứng API Key (không khuyến khích), bỏ comment dòng dưới:
      # - API_KEY=AIzaSy...
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
